import "dotenv/config";
import path from "node:path";
import fs from "fs-extra";
import chalk from "chalk";
import { execa } from "execa";

import { makeRunDir } from "./util/runDir.js";
import { getDefaultModelForProvider, getProviderEnvVar, providerHasConfiguredEnvKey } from "./registry/providers.js";
import { readTextIfExists, writeJson, writeText } from "./util/io.js";
import { loadImageAsBase64 } from "./util/image.js";
import { bundleSpiceIncludes } from "./util/spiceIncludes.js";
import { dispatchPrompt } from "./core/providers/resolver.js";
import { buildEnsemblePrompt, parseEnsembleOutputs } from "./ensemble.js";
import { parseNetlist } from "./netlist/parse.js";
import { netlistToDot } from "./netlist/graph.js";
import { writeReportDocx } from "./report/docx.js";
import { writeReportPdf } from "./report/pdf.js";
import { convertDocxToPdfViaLibreOffice } from "./report/docxToPdf.js";
import { BUILTIN_PROVIDER_NAMES, isBuiltinProviderName } from "./types.js";
import type { BuiltinProviderName, InputImage, ModelAnswer, ProviderName, TaggedImagePath, TaggedInputImage } from "./types.js";
import type { SubcktIntegrationConfig } from "./subckt/types.js";
import { runSubcktIntegration } from "./subckt/integration/integrate.js";

export type RunBatchOptions = {
  questionPath?: string;
  questionText?: string;
  questionFilename?: string;
  baselineNetlistPath?: string;
  baselineNetlistText?: string;
  baselineNetlistFilename?: string;
  baselineImagePath?: string;
  baselineImage?: InputImage;
  /** Optional tagged reference images (paths) to attach as additional context. */
  referenceImagePaths?: TaggedImagePath[];
  /** Optional tagged reference images (embedded base64), for programmatic callers. */
  referenceImages?: TaggedInputImage[];
  /** (Deprecated) Optional oscilloscope trace images (paths) to attach as additional context. */
  traceImagePaths?: string[];
  /** (Deprecated) Optional oscilloscope trace images (embedded base64). */
  traceImages?: InputImage[];
  bundleIncludes?: boolean;
  outdir?: string;
  /** DPI for schematic.png rendering (Graphviz). */
  schematicDpi?: number;
  openaiModel?: string;
  grokModel?: string;
  geminiModel?: string;
  claudeModel?: string;
  /** Providers to query in the fanout step. If omitted, runs all providers. */
  enabledProviders?: ProviderName[];
  /** If true, may prompt for missing baseline inputs when run in a TTY. */
  allowPrompts?: boolean;
  /**
   * Optional SUBCKT integration configuration.
   * When mode is "manual", generates .lib files for the listed components and
   * optionally patches final.cir with .include directives.
   */
  subcktIntegration?: SubcktIntegrationConfig;
};

export type RunBatchResult = {
  runDir: string;
  outputs: {
    reportDocx: string;
    reportPdf: string;
    finalCir: string;
    finalMd: string;
    schematicDot: string;
    schematicPng?: string;
    schematicSvg?: string;
    baselineCir?: string;
    baselineOriginalCir?: string;
    baselineIncludesJson?: string;
    baselineImage?: string;
    referenceImages?: Array<{ tag: string; path: string }>;
    /** (Deprecated) Saved reference images (same as referenceImages paths, without tags). */
    traceImages?: string[];
    answersJson: string;
    /** Path to subckt-manifest.json when SUBCKT integration ran (mode !== "disabled"). */
    subcktManifestPath?: string;
    /** Absolute paths to all .lib files generated by SUBCKT integration. */
    subcktLibPaths?: string[];
    /**
     * Path to final-with-libs.cir when patchFinalCir is true.
     * Contains the ensemble .cir with .include directives prepended.
     */
    patchedCirPath?: string;
  };
};

export type RunBatchLogger = {
  info: (msg: string) => void;
  warn: (msg: string) => void;
  error: (msg: string) => void;
};

type BaselineNetlist = { text?: string; sourcePath?: string };

async function maybePromptForBaselineNetlist(existingPath?: string): Promise<BaselineNetlist> {
  if (!process.stdin.isTTY) return {};

  const { createInterface } = await import("node:readline/promises");
  const { stdin: input, stdout: output } = await import("node:process");

  const rl = createInterface({ input, output });
  try {
    const yn = (await rl.question("No baseline netlist provided. Add one now? [y/N]: ")).trim().toLowerCase();
    if (!(yn === "y" || yn === "yes")) return {};

    const mode = (await rl.question("Provide baseline as (f)ile path or (p)aste? [f/p]: ")).trim().toLowerCase();

    if (mode.startsWith("f")) {
      const fp = (await rl.question("Path to netlist file (.cir): ")).trim();
      if (!fp) return {};
      const ok = await fs.pathExists(fp);
      if (!ok) return {};
      const text = await fs.readFile(fp, "utf-8");
      return { text, sourcePath: fp };
    }

    console.log(chalk.cyan("Paste SPICE netlist now. End with a line containing only ---END---"));
    const lines: string[] = [];
    while (true) {
      const line = await rl.question("");
      if (line.trim() === "---END---") break;
      lines.push(line);
    }
    const pasted = lines.join("\n").trim();
    return pasted ? { text: pasted } : {};
  } finally {
    rl.close();
  }
}

async function loadBaselineNetlist(pathMaybe?: string, allowPrompts = true): Promise<BaselineNetlist> {
  if (pathMaybe && pathMaybe.trim()) {
    const fromFile = await readTextIfExists(pathMaybe);
    if (fromFile && fromFile.trim()) return { text: fromFile, sourcePath: pathMaybe };
  }
  if (!allowPrompts) return {};
  return maybePromptForBaselineNetlist(pathMaybe);
}

async function maybePromptForBaselineImage(existingPath?: string): Promise<string | undefined> {
  if (!process.stdin.isTTY) return undefined;

  const { createInterface } = await import("node:readline/promises");
  const { stdin: input, stdout: output } = await import("node:process");

  const rl = createInterface({ input, output });
  try {
    const yn = (await rl.question("Add a schematic screenshot image? [y/N]: ")).trim().toLowerCase();
    if (!(yn === "y" || yn === "yes")) return undefined;

    const fp = (await rl.question("Path to image file (.png/.jpg/.jpeg/.webp): ")).trim();
    if (!fp) return undefined;
    const ok = await fs.pathExists(fp);
    if (!ok) return undefined;
    return fp;
  } finally {
    rl.close();
  }
}

async function resolveBaselineImage(pathMaybe?: string, allowPrompts = true): Promise<string | undefined> {
  if (pathMaybe && pathMaybe.trim()) return pathMaybe;
  if (!allowPrompts) return undefined;
  return maybePromptForBaselineImage(pathMaybe);
}

function normalizePathList(v: unknown): string[] {
  if (!Array.isArray(v)) return [];
  return v.map((x) => String(x ?? "").trim()).filter(Boolean);
}

function sanitizeStem(name: string): string {
  const base = String(name || "").trim();
  const safe = base.replace(/[^a-zA-Z0-9._-]/g, "_");
  return safe || "image";
}

function sanitizeTag(tag: string): string {
  const base = String(tag || "").trim();
  const safe = base.replace(/[^a-zA-Z0-9._-]/g, "_").replace(/_+/g, "_");
  return safe || "ref";
}

function defaultTagFromFilename(filename: string | undefined, fallback: string): string {
  const base = String(filename || "").trim();
  const stem = base ? base.replace(/\.[^./\\]+$/g, "") : "";
  return sanitizeTag(stem || base || fallback);
}

function uniqueTag(tag: string, used: Map<string, number>): string {
  const t0 = sanitizeTag(tag);
  const n = used.get(t0) ?? 0;
  if (n === 0) {
    used.set(t0, 1);
    return t0;
  }
  const t = `${t0}_${n + 1}`;
  used.set(t0, n + 1);
  used.set(t, 1);
  return t;
}

async function uniqueDestPath(dir: string, filename: string): Promise<string> {
  const base = path.basename(filename || "file");
  const ext = path.extname(base);
  const stem = base.slice(0, base.length - ext.length) || "file";

  let candidate = path.join(dir, base);
  if (!(await fs.pathExists(candidate))) return candidate;
  for (let i = 2; i <= 2000; i++) {
    candidate = path.join(dir, `${stem}_${i}${ext}`);
    if (!(await fs.pathExists(candidate))) return candidate;
  }
  const rand = Math.random().toString(16).slice(2, 10);
  return path.join(dir, `${stem}_${rand}${ext}`);
}

function defaultLogger(): RunBatchLogger {
  return {
    info: (m) => console.log(m),
    warn: (m) => console.warn(m),
    error: (m) => console.error(m),
  };
}

function extFromMimeType(mimeType: string | undefined): string {
  const mt = String(mimeType || "").toLowerCase();
  if (mt === "image/png") return ".png";
  if (mt === "image/jpeg" || mt === "image/jpg") return ".jpg";
  if (mt === "image/webp") return ".webp";
  return ".bin";
}

const ALL_PROVIDERS: BuiltinProviderName[] = [...BUILTIN_PROVIDER_NAMES];

function providersWithApiKeysFromEnv(): BuiltinProviderName[] {
  return ALL_PROVIDERS.filter((provider) => providerHasConfiguredEnvKey(provider));
}

function normalizeEnabledProviders(enabled?: ProviderName[]): BuiltinProviderName[] {
  // If the caller did not explicitly choose providers, default to those that have keys.
  // This avoids noisy warnings (and failed calls) for providers the user isn't using.
  if (enabled === undefined) return providersWithApiKeysFromEnv();
  const set = new Set<BuiltinProviderName>();
  for (const p of enabled) {
    if (isBuiltinProviderName(p)) set.add(p);
  }
  return Array.from(set);
}

function modelForProvider(provider: ProviderName, opts: RunBatchOptions): string {
  switch (provider) {
    case "openai":
      return opts.openaiModel ?? getDefaultModelForProvider(provider);
    case "xai":
      return opts.grokModel ?? getDefaultModelForProvider(provider);
    case "google":
      return opts.geminiModel ?? getDefaultModelForProvider(provider);
    case "anthropic":
      return opts.claudeModel ?? getDefaultModelForProvider(provider);
  }

  return getDefaultModelForProvider(provider);
}

async function askProvider(args: {
  provider: ProviderName;
  prompt: string;
  model: string;
  images?: InputImage[];
  maxTokens?: number;
}): Promise<ModelAnswer> {
  return dispatchPrompt(args);
}

export async function runBatch(opts: RunBatchOptions, logger: RunBatchLogger = defaultLogger()): Promise<RunBatchResult> {
  const allowPrompts = opts.allowPrompts ?? true;

  const enabledProviders = normalizeEnabledProviders(opts.enabledProviders);
  if (!enabledProviders.length) {
    throw new Error(
      opts.enabledProviders === undefined
        ? "No providers enabled (no API keys detected). Set OPENAI_API_KEY/XAI_API_KEY/GEMINI_API_KEY/ANTHROPIC_API_KEY, or explicitly set enabledProviders in the config/UI."
        : "No providers enabled. Select at least one provider.",
    );
  }

  const question = opts.questionText?.trim()
    ? opts.questionText
    : opts.questionPath
      ? await readTextIfExists(opts.questionPath)
      : undefined;
  if (!question?.trim()) {
    throw new Error(
      opts.questionPath
        ? `Could not read question file: ${opts.questionPath}`
        : "Missing required question input (provide questionPath or questionText)",
    );
  }

  const runDir = await makeRunDir(opts.outdir ?? "runs");
  await fs.mkdirp(path.join(runDir, "answers"));
  logger.info(`Run directory: ${runDir}`);

  // Persist embedded question for traceability
  if (opts.questionText?.trim() && !opts.questionPath) {
    const qName = (opts.questionFilename || "question.md").replace(/[^a-zA-Z0-9._-]/g, "_") || "question.md";
    await writeText(path.join(runDir, qName), opts.questionText);
  }

  // Baseline netlist
  const baselineLoaded = opts.baselineNetlistText?.trim()
    ? { text: opts.baselineNetlistText, sourcePath: undefined }
    : await loadBaselineNetlist(opts.baselineNetlistPath, allowPrompts);
  let baselineNetlist = baselineLoaded.text;
  const baselineNetlistSourcePath = baselineLoaded.sourcePath;

  let baselineOriginalCir: string | undefined;
  let baselineIncludesJson: string | undefined;
  let baselineCir: string | undefined;

  if (baselineNetlist) {
    if (opts.bundleIncludes && baselineNetlistSourcePath) {
      const bundled = await bundleSpiceIncludes({
        netlistText: baselineNetlist,
        baselineFilePath: baselineNetlistSourcePath,
        runDir,
        includesDirName: "includes",
      });

      baselineOriginalCir = path.join(runDir, "baseline_original.cir");
      baselineCir = path.join(runDir, "baseline.cir");
      baselineIncludesJson = path.join(runDir, "baseline_includes.json");

      await writeText(baselineOriginalCir, baselineNetlist);
      await writeText(baselineCir, bundled.bundledNetlist);
      await writeJson(baselineIncludesJson, {
        copied: bundled.copied.map((c) => ({
          directive: c.directive,
          originalSpecifier: c.originalSpecifier,
          resolvedSourcePath: c.resolvedSourcePath,
          destPath: c.destPath,
        })),
        missing: bundled.missing,
      });

      if (bundled.missing.length) {
        logger.warn(`Bundled includes: copied ${bundled.copied.length}, missing ${bundled.missing.length}`);
      } else {
        logger.info(`Bundled includes: copied ${bundled.copied.length}`);
      }

      // Use rewritten netlist for prompts
      baselineNetlist = bundled.bundledNetlist;
    } else {
      if (opts.bundleIncludes && !baselineNetlistSourcePath) {
        logger.warn("--bundle-includes was set, but the baseline netlist was pasted (no source file path). Skipping bundling.");
      }
      baselineCir = path.join(runDir, "baseline.cir");
      await writeText(baselineCir, baselineNetlist);
    }
  }

  // Baseline image
  const baselineImagePath = opts.baselineImage ? undefined : await resolveBaselineImage(opts.baselineImagePath, allowPrompts);

  let baselineImage: InputImage | undefined;
  let baselineImageFilename: string | undefined;
  let baselineImageSavedPath: string | undefined;

  if (opts.baselineImage) {
    baselineImage = opts.baselineImage;
    baselineImageFilename = baselineImage.filename || "baseline_schematic";
    const ext = extFromMimeType(baselineImage.mimeType);
    baselineImageSavedPath = path.join(runDir, `baseline_schematic${ext}`);
    await fs.writeFile(baselineImageSavedPath, Buffer.from(baselineImage.base64, "base64"));
  }

  if (baselineImagePath) {
    baselineImage = await loadImageAsBase64(baselineImagePath);
    baselineImageFilename = baselineImage.filename || "baseline_schematic";

    const ext = path.extname(baselineImagePath);
    baselineImageSavedPath = path.join(runDir, `baseline_schematic${ext}`);
    await fs.copy(baselineImagePath, baselineImageSavedPath);
  }

  // Reference images (tagged)
  const usedTags = new Map<string, number>();
  const referenceDir = path.join(runDir, "reference_images");
  const referenceImages: Array<{ tag: string; image: InputImage; savedPath: string; savedFilename: string }> = [];

  const refEmbedded = Array.isArray(opts.referenceImages) ? (opts.referenceImages as TaggedInputImage[]).filter(Boolean) : [];
  const refPaths = Array.isArray(opts.referenceImagePaths) ? (opts.referenceImagePaths as TaggedImagePath[]).filter(Boolean) : [];

  // Legacy (deprecated) trace inputs are treated as reference images too.
  const legacyTraceEmbedded = Array.isArray(opts.traceImages) ? opts.traceImages.filter(Boolean) : [];
  const legacyTracePaths = normalizePathList(opts.traceImagePaths);

  if (refEmbedded.length || refPaths.length || legacyTraceEmbedded.length || legacyTracePaths.length) {
    await fs.mkdirp(referenceDir);
  }

  for (let i = 0; i < refEmbedded.length; i++) {
    const img = refEmbedded[i];
    if (!img?.mimeType || !img?.base64) continue;
    const tag = uniqueTag(img.tag || defaultTagFromFilename(img.filename, `ref_${String(i + 1).padStart(2, "0")}`), usedTags);
    const ext = extFromMimeType(img.mimeType);
    const baseName = sanitizeStem(`${tag}__${img.filename || "ref"}`);
    const dest = await uniqueDestPath(referenceDir, `${baseName}${ext}`);
    await fs.writeFile(dest, Buffer.from(img.base64, "base64"));
    const savedFilename = path.basename(dest);
    referenceImages.push({
      tag,
      image: { mimeType: img.mimeType, base64: img.base64, filename: savedFilename },
      savedPath: dest,
      savedFilename,
    });
  }

  for (let i = 0; i < refPaths.length; i++) {
    const it = refPaths[i];
    const p = String(it?.path || "").trim();
    if (!p) continue;
    const tag = uniqueTag(it.tag || defaultTagFromFilename(path.basename(p), `ref_${String(i + 1).padStart(2, "0")}`), usedTags);
    const img = await loadImageAsBase64(p);
    const ext = path.extname(p) || extFromMimeType(img.mimeType);
    const baseName = sanitizeStem(`${tag}__${path.basename(p, path.extname(p)) || "ref"}`);
    const dest = await uniqueDestPath(referenceDir, `${baseName}${ext}`);
    await fs.copy(p, dest);
    const savedFilename = path.basename(dest);
    referenceImages.push({
      tag,
      image: { mimeType: img.mimeType, base64: img.base64, filename: savedFilename },
      savedPath: dest,
      savedFilename,
    });
  }

  for (let i = 0; i < legacyTraceEmbedded.length; i++) {
    const img = legacyTraceEmbedded[i];
    if (!img?.mimeType || !img?.base64) continue;
    const tag = uniqueTag(defaultTagFromFilename(img.filename, `trace_${String(i + 1).padStart(2, "0")}`), usedTags);
    const ext = extFromMimeType(img.mimeType);
    const baseName = sanitizeStem(`${tag}__${img.filename || "trace"}`);
    const dest = await uniqueDestPath(referenceDir, `${baseName}${ext}`);
    await fs.writeFile(dest, Buffer.from(img.base64, "base64"));
    const savedFilename = path.basename(dest);
    referenceImages.push({
      tag,
      image: { mimeType: img.mimeType, base64: img.base64, filename: savedFilename },
      savedPath: dest,
      savedFilename,
    });
  }

  for (let i = 0; i < legacyTracePaths.length; i++) {
    const p = legacyTracePaths[i];
    if (!p) continue;
    const tag = uniqueTag(defaultTagFromFilename(path.basename(p), `trace_${String(i + 1).padStart(2, "0")}`), usedTags);
    const img = await loadImageAsBase64(p);
    const ext = path.extname(p) || extFromMimeType(img.mimeType);
    const baseName = sanitizeStem(`${tag}__${path.basename(p, path.extname(p)) || "trace"}`);
    const dest = await uniqueDestPath(referenceDir, `${baseName}${ext}`);
    await fs.copy(p, dest);
    const savedFilename = path.basename(dest);
    referenceImages.push({
      tag,
      image: { mimeType: img.mimeType, base64: img.base64, filename: savedFilename },
      savedPath: dest,
      savedFilename,
    });
  }

  const allImages: InputImage[] = [
    ...(baselineImage ? [baselineImage] : []),
    ...referenceImages.map((x) => x.image),
  ];

  const referenceIndexLines = referenceImages.length
    ? [
        "REFERENCE IMAGES (tag -> filename):",
        ...referenceImages.map((x) => `- ${x.tag}: ${x.savedFilename}`),
        "You may reference these in the question text using [[ref:TAG]].",
      ]
    : [];

  // Fanout prompt
  const fanoutPrompt =
    question.trim() +
    (baselineNetlist
      ? `\n\nBASELINE NETLIST (current topology):\n\n\`\`\`spice\n${baselineNetlist.trim()}\n\`\`\`\n`
      : "") +
    (baselineImageFilename ? "\n\nNOTE: A schematic screenshot image is provided as context.\n" : "") +
    (referenceIndexLines.length ? `\n\n${referenceIndexLines.join("\n")}\n` : "");

  // Fanout
  logger.info("Querying models...");

  // Best-effort env-key warnings (providers will still return structured errors if called without a key).
  for (const provider of enabledProviders) {
    const envVar = getProviderEnvVar(provider);
    if (envVar && !process.env[envVar]) {
      logger.warn(`Warning: ${envVar} not set. ${provider} calls will fail.`);
    }
  }

  const fanoutJobs = enabledProviders.map((provider) => {
    const model = modelForProvider(provider, opts);
    const maxTokens = provider === "anthropic" ? 1200 : undefined;
    return askProvider({ provider, prompt: fanoutPrompt, model, images: allImages, maxTokens });
  });
  const answers = await Promise.all<ModelAnswer>(fanoutJobs);

  const answersJson = path.join(runDir, "answers.json");
  await writeJson(answersJson, answers);

  for (const a of answers) {
    const safeModel = a.model.replace(/[^a-zA-Z0-9._-]/g, "_");
    const fname = `${a.provider}_${safeModel}.md`;
    const body = a.error ? `# ERROR\n\n${a.error}` : a.text;
    await writeText(path.join(runDir, "answers", fname), `# ${a.provider} | ${a.model}\n\n${body}\n`);
  }

  // Ensemble
  // Prefer Claude as the ensembler when available, else fall back to the first enabled provider.
  const ensembleProvider: ProviderName = enabledProviders.includes("anthropic") ? "anthropic" : enabledProviders[0];
  const ensembleModel = modelForProvider(ensembleProvider, opts);
  if (ensembleProvider === "anthropic" && !process.env.ANTHROPIC_API_KEY) {
    logger.warn("Warning: ANTHROPIC_API_KEY not set. Ensemble step will fail.");
  }

  logger.info(`Ensembling with ${ensembleProvider}...`);
  const ensemblePrompt = buildEnsemblePrompt({
    question,
    baselineNetlist,
    baselineImageFilename: baselineImageFilename ? path.basename(baselineImageSavedPath ?? baselineImageFilename) : undefined,
    referenceImages: referenceImages.map((x) => ({ tag: x.tag, filename: x.savedFilename })),
    answers,
  });

  const ensembleMaxTokens = ensembleProvider === "anthropic" ? 4800 : undefined;
  const ensemble = await askProvider({
    provider: ensembleProvider,
    prompt: ensemblePrompt,
    model: ensembleModel,
    images: allImages,
    maxTokens: ensembleMaxTokens,
  });
  await writeText(path.join(runDir, "ensemble_raw.txt"), ensemble.text || ensemble.error || "");

  if (ensemble.error || !ensemble.text) {
    throw new Error(`Ensemble failed: ${ensemble.error ?? "No text returned"}`);
  }

  const out = parseEnsembleOutputs(ensemble.text);
  const finalMd = path.join(runDir, "final.md");
  const finalCir = path.join(runDir, "final.cir");
  const finalJson = path.join(runDir, "final.json");

  const missingSpice = !out.spiceNetlist.trim();
  const missingJson = !out.circuitJson.trim();

  if (missingSpice) {
    logger.error(
      "Ensemble output did not include a <spice_netlist> block (or a recoverable SPICE code block). final.cir will contain an error placeholder.",
    );
  }
  if (missingJson) {
    logger.warn(
      "Ensemble output did not include a <circuit_json> block (or a recoverable JSON block). final.json will contain an error placeholder.",
    );
  }

  const finalMarkdownBest = out.finalMarkdown.trim()
    ? out.finalMarkdown
    : "# Ensemble output\n\n(Ensemble did not provide <final_markdown>; see ensemble_raw.txt.)\n";

  const finalMdText =
    finalMarkdownBest +
    (missingSpice
      ? "\n> WARNING: Missing SPICE netlist block; see ensemble_raw.txt.\n"
      : "");

  const finalCirText = missingSpice
    ? [
        "* ERROR: Ensemble output missing <spice_netlist> block.",
        "* See ensemble_raw.txt for the full model output.",
        "* baseline.cir contains the baseline topology netlist.",
        ".end",
        "",
      ].join("\n")
    : out.spiceNetlist;

  const finalJsonText = missingJson
    ? JSON.stringify(
        {
          error: "Ensemble output missing <circuit_json> block.",
          assumptions: [],
          probes: [],
          bom: [],
          notes: ["See ensemble_raw.txt for full model output."],
        },
        null,
        2,
      ) + "\n"
    : out.circuitJson;

  // --- SUBCKT integration (Phase H.5) ---
  let subcktManifestPath: string | undefined;
  let subcktLibPaths: string[] = [];
  let subcktReportSummary: string[] = [];
  let patchedCirPath: string | undefined;

  if (opts.subcktIntegration && opts.subcktIntegration.mode !== "disabled") {
    try {
      logger.info("Running SUBCKT integration...");
      const integrationOut = await runSubcktIntegration({
        config: opts.subcktIntegration,
        runDir,
        finalCirText,
        log: logger.info,
      });
      subcktManifestPath = integrationOut.manifestPath;
      subcktLibPaths = integrationOut.result.generatedLibPaths;
      subcktReportSummary = integrationOut.result.reportSummary;

      if (integrationOut.result.updatedCirText) {
        const patchedCirFile = path.join(runDir, "final-with-libs.cir");
        await writeText(patchedCirFile, integrationOut.result.updatedCirText);
        patchedCirPath = patchedCirFile;
        logger.info(`Wrote patched netlist: final-with-libs.cir`);
      }

      if (integrationOut.status === "failed" && opts.subcktIntegration.requireValidationPass) {
        logger.error("SUBCKT integration failed and requireValidationPass is true.");
      }
    } catch (e: any) {
      logger.warn(`SUBCKT integration step failed: ${String(e?.message ?? e)}`);
    }
  }

  await writeText(finalMd, finalMdText);
  await writeText(finalCir, finalCirText);
  await writeText(finalJson, finalJsonText);

  // Connectivity diagram
  logger.info("Generating connectivity diagram...");
  let schematicPng: string | undefined;
  let schematicSvg: string | undefined;
  const schematicDot = path.join(runDir, "schematic.dot");
  try {
    const finalNetlist = out.spiceNetlist || "";
    const baselineNetlistText = baselineNetlist || "";

    let sourceLabel = "final";
    let schematicNetlist = finalNetlist;

    if (!finalNetlist.trim() && baselineNetlistText.trim()) {
      sourceLabel = "baseline";
      schematicNetlist = baselineNetlistText;
      logger.warn("Final netlist is empty; generating schematic from baseline netlist instead.");
    }

    let comps = parseNetlist(schematicNetlist);
    if (comps.length === 0 && sourceLabel !== "baseline" && baselineNetlistText.trim()) {
      const baselineComps = parseNetlist(baselineNetlistText);
      if (baselineComps.length) {
        sourceLabel = "baseline";
        schematicNetlist = baselineNetlistText;
        comps = baselineComps;
        logger.warn("Final netlist did not yield any components; generating schematic from baseline netlist instead.");
      }
    }

    let dot = netlistToDot(comps);
    if (sourceLabel !== "final") {
      dot = dot.replace(
        "digraph G {",
        `digraph G {\n  // NOTE: Rendered from ${sourceLabel} netlist because final netlist was empty or unparseable.`,
      );
    }
    await writeText(schematicDot, dot);

    const pngPath = path.join(runDir, "schematic.png");
    const svgPath = path.join(runDir, "schematic.svg");
    try {
      const dpiCandidate = opts.schematicDpi as number;
      const dpi = Number.isFinite(dpiCandidate) && dpiCandidate > 0 ? dpiCandidate : 600;
      await execa("dot", [`-Gdpi=${dpi}`, "-Tpng", schematicDot, "-o", pngPath]);
      schematicPng = pngPath;
      logger.info("Rendered schematic.png via Graphviz.");
    } catch (e: any) {
      if (String(e?.code ?? "") === "ENOENT") {
        logger.warn("Graphviz 'dot' not found; wrote schematic.dot only.");
      } else {
        logger.warn("Graphviz failed to render schematic.png; wrote schematic.dot only.");
      }
    }

    // SVG is ideal for zooming/printing.
    if (schematicPng || schematicNetlist.trim()) {
      try {
        await execa("dot", ["-Tsvg", schematicDot, "-o", svgPath]);
        schematicSvg = svgPath;
        logger.info("Rendered schematic.svg via Graphviz.");
      } catch (e: any) {
        if (String(e?.code ?? "") !== "ENOENT") {
          logger.warn("Graphviz failed to render schematic.svg; continuing.");
        }
      }
    }
  } catch (e: any) {
    logger.warn(`Schematic generation skipped: ${String(e?.message ?? e)}`);
  }

  // Word report
  logger.info("Writing report.docx...");
  const reportDocx = path.join(runDir, "report.docx");

  const answersForReport = answers.map((a) => {
    const body = a.error ? `# ERROR\n\n${a.error}` : (a.text || "(No output)");
    return { heading: `${a.provider} | ${a.model}`, markdown: body };
  });

  await writeReportDocx({
    outPath: reportDocx,
    title: "AI Schematics — Ensemble Report",
    question,
    finalMarkdown: finalMarkdownBest,
    spiceNetlist: out.spiceNetlist,
    baselineSchematicPath: baselineImageSavedPath,
    referenceImages: referenceImages.map((x) => ({ tag: x.tag, path: x.savedPath })),
    connectivitySchematicPngPath: schematicPng,
    answers: answersForReport,
    generatedSubcktModels: subcktReportSummary.length ? subcktReportSummary : undefined,
  });

  const reportPdf = path.join(runDir, "report-auto.pdf");
  logger.info("Writing report-auto.pdf...");

  const converted = await convertDocxToPdfViaLibreOffice({ docxPath: reportDocx, pdfOutPath: reportPdf });
  if (converted.ok) {
    logger.info(`Rendered report-auto.pdf from report.docx via ${converted.method}.`);
  } else {
    logger.warn(`DOCX→PDF conversion not available (${converted.reason}); falling back to built-in PDF renderer.`);
    await writeReportPdf({
      outPath: reportPdf,
      title: "AI Schematics — Ensemble Report",
      question,
      finalMarkdown: finalMarkdownBest,
      spiceNetlist: out.spiceNetlist,
      baselineSchematicPath: baselineImageSavedPath,
      referenceImages: referenceImages.map((x) => ({ tag: x.tag, path: x.savedPath })),
      connectivitySchematicPngPath: schematicPng,
      answers: answersForReport,
    });
  }

  logger.info("Done.");

  return {
    runDir,
    outputs: {
      reportDocx,
      reportPdf,
      finalCir,
      finalMd,
      schematicDot,
      schematicPng,
      schematicSvg,
      baselineCir,
      baselineOriginalCir,
      baselineIncludesJson,
      baselineImage: baselineImageSavedPath,
      referenceImages: referenceImages.length
        ? referenceImages.map((x) => ({ tag: x.tag, path: x.savedPath }))
        : undefined,
      traceImages: referenceImages.length ? referenceImages.map((x) => x.savedPath) : undefined,
      answersJson,
      subcktManifestPath,
      subcktLibPaths: subcktLibPaths.length ? subcktLibPaths : undefined,
      patchedCirPath,
    },
  };
}
